name: Snake Daily Animation

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean up old files and switch to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin output
          git switch output || git switch --orphan output
          git pull origin output || true
          rm -f snake*.svg snake*.gif
          rm -rf dist/

      - name: Generate Snake animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: AlexeyFloppa
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake.gif

      - name: Copy snake files into output branch
        run: |
          cp -r dist/* .

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update GitHub contribution snake"
          branch: output
